### ISSUE TITLE
long loading 

### ISSUE THREAD

**Issue by Que0Le** [FriendsOfFlarum/discussion-thumbnail#1]
Hi,
 I love this extension, however there is a problem: Loading image really slow if embed image used in post (first image, ofc).

This raises (imho) a few solutions:
1. Auto download and cache (first) image if they are not saved in server. Problem: copyright?
2. Create other extension: Allow user choose image for their post to use as post-thumbnail (replace user 's avatar). This photo will be explicit download locally.

**Comment by dsevillamartin** [comment]
Those alternative solutions have already been considered. I decided to not implement them because it would increase the complexity of the extension (development) and how easy it was to use for the user.

Can you elaborate on "Loading image really slow if embed image used in post"? Do you just mean large images take a while to load? If so, that's why I implemented lazy loading - so images only load when they are visible on the screen (only images set by this extension).

**Comment by Que0Le** [comment]
In your demonstration video you can see page done loading, however lazy loading still waiting for remote images being load. If there are 10 discussions in discussion list each with remote images => it doesn't look good, 10 "avatar pics" with waiting circle. I would prefer an other extension which allow user to choose pic as post thumbnail (2) :)

**Comment by dsevillamartin** [comment]
I understand what you are asking for. I don't know if anyone will create that extension (including me) yet, anyway. Sorry :/.

**Comment by Que0Le** [comment]
ok thanks
